name: learn-github-actions

on: 
  workflow_dispatch:
  # push:
  
jobs:
  run-int-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: yarn install

      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          headless: true
          command: yarn cypress run
